// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"database/sql"
)

type Account struct {
	ID        int64        `json:"id"`
	Owner     string       `json:"owner"`
	Currency  string       `json:"currency"`
	Balance   int64        `json:"balance"`
	CreatedAt sql.NullTime `json:"createdAt"`
}

type Entry struct {
	ID        int64 `json:"id"`
	AccountID int64 `json:"accountID"`
	// could be negative or positive value
	Amount    int64        `json:"amount"`
	CreatedAt sql.NullTime `json:"createdAt"`
}

type Transfer struct {
	ID            int64 `json:"id"`
	FromAccountID int64 `json:"fromAccountID"`
	ToAccountID   int64 `json:"toAccountID"`
	// must be positive value
	Amount    int64        `json:"amount"`
	CreatedAt sql.NullTime `json:"createdAt"`
}
